export const projects = [
  {
    src: "/foodflux-image-new.jpg",
    title: "FoodFlux",
    description:
      "A completely distributed microservices system demonstrating food delivery services and inter-service communication.",
    slug: "foodflux",
    githublink:
      "https://github.com/ShahuKor/FoodFlux-Distributed-Food-Ordering",
    status: "Completed",
    type: "Full Stack",
    overview:
      "FoodFlux is a distributed food ordering platform built with microservices. It lets users browse restaurants, place orders, and track delivery status in real time. The system demonstrates event-driven architecture with Kafka, fault tolerance patterns, and WebSocket notifications across independent backend services.",
    tasks: [
      "Browse restaurants and view menus as a customer",
      "Add items to cart and place food orders",
      "Receive real-time order tracking updates",
      "Manage restaurant orders and status views for kitchen staff",
      "Driver dashboard for accepting and updating delivery status",
      "Handle authentication and role-based access control",
      "Simulate fault tolerance using circuit breaker patterns",
    ],
    reasons: [
      "To learn and demonstrate distributed systems and microservices architecture",
      "To practice event-driven communication using Kafka and asynchronous patterns",
      "To explore real-time notifications and WebSockets in full-stack apps",
      "To implement fault tolerance and service resilience in a real-world use case",
    ],
    techstack: [
      "Node.js",
      "Express.js",
      "Next.js",
      "React",
      "Kafka",
      "KafkaJS",
      "PostgreSQL",
      "MongoDB",
      "Docker",
      "Docker Compose",
      "Kubernetes",
      "Socket.io",
      "JWT",
      "bcrypt",
      "Tailwind CSS",
      "TypeScript",
    ],
  },
  {
    src: "/quib-image-new.jpg",
    title: "Quib",
    description:
      "A production-ready SaaS platform that converts PDFs into interactive, reels-style summaries for a modern and engaging learning experience.",
    slug: "quib",
    githublink: "https://github.com/ShahuKor/Quib",
    status: "Developing",
    type: "Full Stack",
    overview:
      "Quib is a full-stack SaaS application that allows users to upload PDFs and instantly receive beautifully structured, easy-to-understand summaries. Instead of traditional text outputs, the summaries are displayed in an interactive reels-style format, making learning more engaging and user-friendly. The platform includes authentication, subscription billing, secure file handling, and scalable backend architecture designed for real-world production use.",
    tasks: [
      "Secure PDF upload and storage",
      "Extract and process content from uploaded PDFs",
      "Generate AI-powered summaries using ChatGPT and Gemini",
      "Structure summaries into clean, readable sections",
      "Display summaries in an interactive reels-style component",
      "User authentication and account management with Clerk",
      "Subscription plans and payment handling via Stripe",
      "Database management using PostgreSQL (Neon DB)",
      "Responsive and modern UI built with Tailwind and shadcn/ui",
    ],
    reasons: [
      "To make learning from long PDFs faster and more engaging",
      "To improve knowledge retention using structured and visual summaries",
      "To build a real-world, production-grade SaaS product",
      "To combine AI capabilities with modern full-stack development",
      "To gain hands-on experience with authentication, payments, and scalable architecture",
    ],
    techstack: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "shadcn/ui",
      "UploadThing",
      "Neon DB",
      "PostgreSQL",
      "Clerk",
      "Stripe",
      "OpenAI (ChatGPT)",
      "Google Gemini",
    ],
  },
  {
    src: "/cutthatpart-image.jpg",
    title: "CutThatPart",
    description:
      "Share parts of a YouTube videos instantly without downloading it or screen recording, with a personal share link.",
    slug: "cutthatpart",
    githublink: "https://github.com/ShahuKor/CutThatPart",
    status: "Developing",
    type: "Full Stack",
    overview:
      "CutThatPart is a web app that lets users share only a specific portion of a YouTube video instead of sending the entire video or screen recording it. Users paste a YouTube URL, select the start and end timestamps, and the app processes and generates a shareable video link with a clean viewing interface. It simplifies video clipping and sharing while handling video processing efficiently on the backend.",
    tasks: [
      "Accept YouTube video URL input from users",
      "Allow users to specify start and end timestamps",
      "Process video clips using yt-dlp and FFmpeg",
      "Generate trimmed video files dynamically",
      "Upload processed clips to AWS S3",
      "Create a unique shareable link for each clip",
      "Display a clean video player page with sharer details",
      "Handle background video processing using AWS SQS",
      "Deploy scalable backend services using AWS ECS and Docker",
      "Store metadata (clip info, sharer name, timestamps) in PostgreSQL (Neon DB)",
    ],
    reasons: [
      "To solve the hassle of screen recording or downloading full YouTube videos just to share a small part",
      "To build a strong real-world full stack project",
      "To work with video processing tools like yt-dlp and FFmpeg",
      "To gain hands-on experience with AWS cloud services",
      "To design a scalable backend architecture using queues and containers",
    ],
    techstack: [
      "Next.js",
      "React",
      "Node.js",
      "TypeScript",
      "PostgreSQL",
      "Neon DB",
      "AWS S3",
      "AWS SQS",
      "AWS ECS",
      "AWS ECR",
      "Docker",
      "yt-dlp",
      "FFmpeg",
    ],
  },
  {
    src: "/cliply-image-new.jpg",
    title: "Cliply",
    description:
      "An AI-powered media optimization & sharing platform with contextual image cropping, smart video compression, and a public showcase wall.",
    slug: "cliply",
    githublink: "https://github.com/ShahuKor/About-Cliply",
    status: "Completed",
    type: "Full Stack",
    overview:
      "Cliply is a full-stack web application that allows users to upload images and videos, automatically optimize them using AI, and share them publicly. It simplifies media processing by offering smart image cropping and efficient video compression, all through a clean and responsive interface.",
    tasks: [
      "Upload images and videos for processing",
      "Automatically crop images using AI-based contextual detection",
      "Compress videos while maintaining visual quality",
      "Preview processed media before downloading",
      "Browse publicly shared media on a showcase wall",
      "Create an account and securely access media tools",
      "Store and manage uploaded media content",
    ],
    reasons: [
      "To explore AI-powered media optimization in real-world applications",
      "To build a complete full-stack platform with authentication and media handling",
      "To understand cloud-based media processing workflows",
      "To create a practical project demonstrating modern web architecture",
    ],
    techstack: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "DaisyUI",
      "Clerk ",
      "Cloudinary AI",
      "NeonDB",
      "PostgreSQL",
      "Prisma ORM",
      "Vercel",
    ],
  },
  {
    src: "/webchat-ai-image-new.jpg",
    title: "WebChat AI",
    description:
      "A RAG chatbot that makes ChatGPT get context of any URL or website, built with Streamlit and LangChain.",
    slug: "webchat-ai",
    githublink: "https://github.com/ShahuKor/WebChat-Ai",
    status: "Completed",
    type: "Full Stack",
    overview:
      "WebChat AI is a browser content-aware chatbot that lets users paste a URL and chat with the content of that webpage. It extracts text from any site, processes it with LangChain embeddings, and provides contextual AI responses through a simple Streamlit UI.",
    tasks: [
      "Take a website link as input and scrape its textual content.",
      "Split the scraped text into chunks for embedding.",
      "Store text embeddings in a vector database for RAG retrieval.",
      "Accept user queries and perform semantic search over the page content.",
      "Generate context-aware answers using an LLM based on the retrieved website content.",
      "Display chat history and responses within a Streamlit interface.",
    ],
    reasons: [
      "To build a tool that lets ChatGPT understand and answer questions using the actual content of any URL.",
      "To learn and apply LangChain and RAG techniques in a real project.",
      "To provide an easy UI for contextual website Q&A without manual data prep.",
      "To explore how vector embeddings can enhance chatbot relevance.",
    ],
    techstack: [
      "Python",
      "Streamlit",
      "LangChain",
      "BeautifulSoup ",
      "Embeddings and Vector Database",
      "OpenAI / GPT-4",
    ],
  },
  {
    src: "/learnstack-image.jpg",
    title: "LearnStack",
    description:
      "A modular backend system for an online learning platform with user management, course delivery, enrollment and payment integration.",
    slug: "learnstack",
    githublink: "https://github.com/ShahuKor/learnstack-backend",
    status: "Completed",
    type: "Backend",
    overview:
      "LearnStack is the core backend for a learning platform (LMS) that handles user authentication, course management, enrollments, role-based access control, and multi-provider payment flows using modern web technologies.",
    tasks: [
      "Authenticate users and manage identities",
      "Create, update and retrieve courses (course delivery)",
      "Handle student enrollments and track participation",
      "Implement role-based access control (RBAC)",
      "Process payments through Stripe and Razorpay",
    ],
    reasons: [
      "To build a real-world backend for a learning platform",
      "To practice building production grade REST APIs and code with Node.js",
      "To learn how to integrate databases and payment providers",
      "To improve backend architectural skills",
    ],
    techstack: ["Node.js", "Express.js", "MongoDB", "Stripe", "Razorpay"],
  },
];
